#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
CONFIG_FILE="${PROJECT_ROOT}/config/cluster.env"
DRY_RUN=false

usage() {
  cat <<'EOF'
Usage: configure-and-start.sh [--config FILE] [--dry-run] [--help]

Discover node resources and addresses, install a shared slurm.conf, prepare
runtime storage, start the Slurm daemons, and verify both workers become idle.
EOF
}

while (($# > 0)); do
  case "$1" in
    --config)
      [[ $# -ge 2 ]] || { echo "Error: --config requires a file." >&2; exit 2; }
      CONFIG_FILE="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Error: unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

command -v multipass >/dev/null 2>&1 || {
  echo "Error: Multipass is not installed or is not in PATH." >&2
  exit 1
}
[[ -r "$CONFIG_FILE" ]] || {
  echo "Error: cannot read configuration: $CONFIG_FILE" >&2
  exit 1
}

# shellcheck source=../../config/cluster.env
source "$CONFIG_FILE"
LOG_DIR="${LOG_DIR:-logs}"
[[ "$LOG_DIR" == /* ]] || LOG_DIR="${PROJECT_ROOT}/${LOG_DIR}"
# shellcheck source=../lib/observability.sh
source "${SCRIPT_DIR}/../lib/observability.sh"
init_observability "04-slurm" "$LOG_DIR"

required_variables=(
  CONTROLLER_NAME WORKER1_NAME WORKER2_NAME CLUSTER_NAME PARTITION_NAME
  MEMORY_RESERVE_MB NODE_REGISTRATION_TIMEOUT_SECONDS LOG_DIR
)
for variable in "${required_variables[@]}"; do
  [[ -n "${!variable:-}" ]] || {
    log ERROR "$variable is missing or empty in $CONFIG_FILE"
    exit 1
  }
done
for name_variable in CONTROLLER_NAME WORKER1_NAME WORKER2_NAME CLUSTER_NAME PARTITION_NAME; do
  [[ "${!name_variable}" =~ ^[a-zA-Z0-9_-]+$ ]] || {
    log ERROR "$name_variable contains unsupported characters: ${!name_variable}"
    exit 1
  }
done
[[ "$MEMORY_RESERVE_MB" =~ ^[0-9]+$ ]] || {
  log ERROR "MEMORY_RESERVE_MB must be a non-negative integer"
  exit 1
}
[[ "$NODE_REGISTRATION_TIMEOUT_SECONDS" =~ ^[1-9][0-9]*$ ]] || {
  log ERROR "NODE_REGISTRATION_TIMEOUT_SECONDS must be a positive integer"
  exit 1
}

nodes=("$CONTROLLER_NAME" "$WORKER1_NAME" "$WORKER2_NAME")
workers=("$WORKER1_NAME" "$WORKER2_NAME")
if [[ "$CONTROLLER_NAME" == "$WORKER1_NAME" ||
      "$CONTROLLER_NAME" == "$WORKER2_NAME" ||
      "$WORKER1_NAME" == "$WORKER2_NAME" ]]; then
  log ERROR "Every node must have a unique name"
  exit 1
fi

get_ipv4() {
  local node="$1"
  local address
  address="$(multipass exec "$node" -- hostname -I | awk '{print $1}')"
  [[ "$address" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || {
    log ERROR "Could not discover an IPv4 address for $node: ${address:-<empty>}"
    return 1
  }
  printf '%s' "$address"
}

resource_value() {
  local resource_line="$1"
  local key="$2"
  local token
  for token in $resource_line; do
    if [[ "$token" == "$key="* ]]; then
      printf '%s' "${token#*=}"
      return 0
    fi
  done
  return 1
}

log INFO "Phase 1/6: discover node addresses and worker resources"
for node in "${nodes[@]}"; do
  multipass info "$node" >/dev/null 2>&1 || {
    log ERROR "Multipass instance does not exist or is unavailable: $node"
    exit 1
  }
done

controller_ip="$(get_ipv4 "$CONTROLLER_NAME")"
node_lines=()
for worker in "${workers[@]}"; do
  worker_ip="$(get_ipv4 "$worker")"
  detected="$(multipass exec "$worker" -- slurmd -C | sed -n '1p')"
  resource_fields=()
  for key in CPUs Boards SocketsPerBoard CoresPerSocket ThreadsPerCore; do
    value="$(resource_value "$detected" "$key")" || {
      log ERROR "slurmd -C did not report $key on $worker: $detected"
      exit 1
    }
    [[ "$value" =~ ^[1-9][0-9]*$ ]] || {
      log ERROR "Invalid $key reported by $worker: $value"
      exit 1
    }
    resource_fields+=("$key=$value")
  done
  detected_memory="$(resource_value "$detected" RealMemory)" || {
    log ERROR "slurmd -C did not report RealMemory on $worker: $detected"
    exit 1
  }
  [[ "$detected_memory" =~ ^[1-9][0-9]*$ ]] || {
    log ERROR "Invalid RealMemory reported by $worker: $detected_memory"
    exit 1
  }
  ((detected_memory > MEMORY_RESERVE_MB)) || {
    log ERROR "Memory reserve ($MEMORY_RESERVE_MB MB) leaves no usable RAM on $worker"
    exit 1
  }
  usable_memory=$((detected_memory - MEMORY_RESERVE_MB))
  node_lines+=("NodeName=$worker NodeAddr=$worker_ip ${resource_fields[*]} RealMemory=$usable_memory State=UNKNOWN")
  log INFO "Discovered: node=$worker, ipv4=$worker_ip, detected_memory=${detected_memory}MB, configured_memory=${usable_memory}MB"
done

slurm_configuration="# Generated by modules/04-slurm/configure-and-start.sh
ClusterName=$CLUSTER_NAME
SlurmctldHost=$CONTROLLER_NAME($controller_ip)
AuthType=auth/munge
SlurmUser=slurm
SlurmdUser=root
StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
ReturnToService=2
ProctrackType=proctrack/linuxproc
TaskPlugin=task/none
MpiDefault=none
SwitchType=switch/none
SlurmctldLogFile=/var/log/slurmctld.log
SlurmdLogFile=/var/log/slurmd.log
${node_lines[0]}
${node_lines[1]}
PartitionName=$PARTITION_NAME Nodes=${WORKER1_NAME},${WORKER2_NAME} Default=YES MaxTime=INFINITE State=UP"

if [[ "$DRY_RUN" == true ]]; then
  log INFO "Generated slurm.conf follows"
  printf '%s\n' "$slurm_configuration"
  log INFO "Dry run finished; no guest files, directories, or services were changed"
  exit 0
fi

log INFO "Phase 2/6: prepare Slurm runtime storage and logs"
multipass exec "$CONTROLLER_NAME" -- sudo install -d -o slurm -g slurm -m 0755 /var/spool/slurmctld
multipass exec "$CONTROLLER_NAME" -- sudo install -o slurm -g slurm -m 0644 /dev/null /var/log/slurmctld.log
for worker in "${workers[@]}"; do
  multipass exec "$worker" -- sudo install -d -o root -g root -m 0755 /var/spool/slurmd
  multipass exec "$worker" -- sudo install -o root -g root -m 0644 /dev/null /var/log/slurmd.log
done

log INFO "Phase 3/6: install one identical Slurm configuration on every node"
expected_hash="$(printf '%s\n' "$slurm_configuration" | shasum -a 256 | awk '{print $1}')"
for node in "${nodes[@]}"; do
  printf '%s\n' "$slurm_configuration" |
    multipass exec "$node" -- sudo sh -c 'install -d -o root -g root -m 0755 /etc/slurm; install -o root -g root -m 0644 /dev/stdin /etc/slurm/slurm.conf'
  observed_hash="$(multipass exec "$node" -- sudo sha256sum /etc/slurm/slurm.conf | awk '{print $1}')"
  [[ "$observed_hash" == "$expected_hash" ]] || {
    log ERROR "Configuration hash mismatch: node=$node, expected=$expected_hash, observed=$observed_hash"
    exit 1
  }
  log INFO "Configuration verified: node=$node, sha256=$observed_hash"
done

log INFO "Phase 4/6: verify authentication and daemon prerequisites"
for node in "${nodes[@]}"; do
  [[ "$(multipass exec "$node" -- systemctl is-active munge)" == active ]] || {
    log ERROR "MUNGE is not active on $node"
    exit 1
  }
done

log INFO "Phase 5/6: enable and restart Slurm services"
start_slurm_service() {
  local node="$1"
  local service="$2"
  local service_state

  service_state="$(multipass exec "$node" -- systemctl is-active "$service" 2>/dev/null || true)"
  if [[ "$service_state" == active || "$service_state" == activating || "$service_state" == deactivating ]]; then
    log WARNING "Terminating the existing $service instance on $node to load the generated configuration"
    multipass exec "$node" -- sudo systemctl kill --kill-whom=main --signal=KILL "$service"
  fi
  multipass exec "$node" -- sudo systemctl reset-failed "$service" >/dev/null 2>&1 || true
  multipass exec "$node" -- sudo systemctl enable --no-reload "$service"
  if ! multipass exec "$node" -- sudo systemctl start "$service"; then
    multipass exec "$node" -- sudo journalctl -u "$service" -n 50 --no-pager || true
    log ERROR "$service failed to start on $node"
    return 1
  fi
}

multipass exec "$CONTROLLER_NAME" -- sudo systemctl daemon-reload
for worker in "${workers[@]}"; do
  multipass exec "$worker" -- sudo systemctl daemon-reload
done
start_slurm_service "$CONTROLLER_NAME" slurmctld
for worker in "${workers[@]}"; do
  start_slurm_service "$worker" slurmd
done

log INFO "Phase 6/6: wait for both workers to register as idle"
deadline=$((SECONDS + NODE_REGISTRATION_TIMEOUT_SECONDS))
while true; do
  idle_nodes="$(multipass exec "$CONTROLLER_NAME" -- sinfo -h -N -p "$PARTITION_NAME" -t idle -o '%N' | sort -u)"
  if grep -Fxq "$WORKER1_NAME" <<<"$idle_nodes" && grep -Fxq "$WORKER2_NAME" <<<"$idle_nodes"; then
    break
  fi
  if ((SECONDS >= deadline)); then
    log ERROR "Workers did not both reach IDLE within ${NODE_REGISTRATION_TIMEOUT_SECONDS}s"
    multipass exec "$CONTROLLER_NAME" -- sinfo -N -l || true
    multipass exec "$CONTROLLER_NAME" -- scontrol show nodes || true
    exit 1
  fi
  sleep 2
done

multipass exec "$CONTROLLER_NAME" -- sinfo -N -l
controller_ping="$(multipass exec "$CONTROLLER_NAME" -- scontrol ping)"
grep -Fq "is UP" <<<"$controller_ping" || {
  log ERROR "Controller ping did not report UP: $controller_ping"
  exit 1
}
for node in "${nodes[@]}"; do
  service=slurmd
  [[ "$node" == "$CONTROLLER_NAME" ]] && service=slurmctld
  active_state="$(multipass exec "$node" -- systemctl is-active "$service")"
  enabled_state="$(multipass exec "$node" -- systemctl is-enabled "$service")"
  [[ "$active_state" == active && "$enabled_state" == enabled ]] || {
    log ERROR "Service validation failed: node=$node, service=$service, active=$active_state, enabled=$enabled_state"
    exit 1
  }
done
log INFO "Slurm is healthy; both workers are registered and idle"
